# Generated by Django 4.0 on 2024-07-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_country_alter_contact_options_alter_network_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
